P8105 HW 6
================
Grace Liu
11/27/2018

P8105 Homework 6
----------------

### Problem 1

``` r
# Create a city_state variable (e.g. “Baltimore, MD”), and a binary variable indicating whether the homicide is solved. Omit cities Dallas, TX; Phoenix, AZ; and Kansas City, MO – these don’t report victim race. Also omit Tulsa, AL – this is a data entry mistake. Modifiy victim_race to have categories white and non-white, with white as the reference category. Be sure that victim_age is numeric.

homicides = 
  read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>% 
  mutate(city_state = paste(city, state, sep = ", "),
         victim_race = ifelse(victim_race != "White", "Non-White", "White"),
         resolved = ifelse(disposition == "Closed by arrest", 1, 0),
         victim_race = fct_relevel(victim_race, "White")) %>% 
  transform(reported_date = as.Date(as.character(reported_date), "%Y%m%d"), 
            victim_age = as.numeric(victim_age)) %>% 
  select(uid, reported_date, city_state, everything()) %>% 
  select(-city, -state) %>% 
  filter(!city_state %in% c("Tulsa, AL", "Dallas, TX", "Phoenix, AZ", "Kansas City, MO")) %>% 
  janitor::clean_names()
```

    ## Parsed with column specification:
    ## cols(
    ##   uid = col_character(),
    ##   reported_date = col_integer(),
    ##   victim_last = col_character(),
    ##   victim_first = col_character(),
    ##   victim_race = col_character(),
    ##   victim_age = col_character(),
    ##   victim_sex = col_character(),
    ##   city = col_character(),
    ##   state = col_character(),
    ##   lat = col_double(),
    ##   lon = col_double(),
    ##   disposition = col_character()
    ## )

    ## Warning in eval(substitute(list(...)), `_data`, parent.frame()): NAs
    ## introduced by coercion

``` r
# For the city of Baltimore, MD, use the glm function to fit a logistic regression with resolved vs unresolved as the outcome and victim age, sex and race (as just defined) as predictors. Save the output of glm as an R object; apply the broom::tidy to this object; and obtain the estimate and confidence interval of the adjusted odds ratio for solving homicides comparing non-white victims to white victims keeping all other variables fixed.

hom_baltimore = homicides %>% 
  filter(city_state == "Baltimore, MD")

fit_baltimore = hom_baltimore%>% 
  glm(resolved ~ victim_age + victim_sex + victim_race, data = ., family = binomial()) 

fit_baltimore %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate),
         OR_lower = exp(estimate - 1.96*std.error),
         OR_upper = exp(estimate + 1.96*std.error)) %>%
  select(term, log_OR = estimate, OR, OR_upper, OR_lower, p.value) %>% 
  knitr::kable(digits = 3)
```

| term                  |  log\_OR|     OR|  OR\_upper|  OR\_lower|  p.value|
|:----------------------|--------:|------:|----------:|----------:|--------:|
| (Intercept)           |    1.186|  3.274|      5.186|      2.067|    0.000|
| victim\_age           |   -0.007|  0.993|      0.999|      0.987|    0.032|
| victim\_sexMale       |   -0.888|  0.412|      0.537|      0.315|    0.000|
| victim\_raceNon-White |   -0.820|  0.441|      0.620|      0.313|    0.000|

Homicides in which the victim is non-white are far less likely to be resolved compared to homicides where the victim is white. In cases with non-white victims, the odds of solving the homicide are 0.441 times that of cases with white victims (95% CI: 0.315, 0.620).

``` r
# Now run glm for each of the cities in your dataset, and extract the adjusted odds ratio (and CI) for solving homicides comparing non-white victims to white victims. Do this within a “tidy” pipeline, making use of purrr::map, list columns, and unnest as necessary to create a dataframe with estimated ORs and CIs for each city.

hom_allcities = homicides %>%
  group_by(city_state) %>% 
  nest() %>% 
  mutate(models = map(data, ~glm(resolved ~ victim_age + victim_sex + victim_race, data = ., family = binomial())),
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest() %>%
  filter(term == "victim_raceNon-White") %>% 
  mutate(OR = exp(estimate),
         OR_lower = exp(estimate - 1.96*std.error),
         OR_upper = exp(estimate + 1.96*std.error)) %>%
  select(city_state, log_OR = estimate, OR, OR_upper, OR_lower, p.value) %>% 
  knitr::kable(digits = 3)
```

``` r
# Create a plot that shows the estimated ORs and CIs for each city. Organize cities according to estimated OR, and comment on the plot.
```
